version: '3.7'
services:

  postgresqldb:
    container_name: postgresqldb
    image: postgres:15-alpine3.16
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_booking_data:/data/postgres
      - ~/IdeaProjects/test3/booking/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      TZ: 'Europe/Warsaw'
      PGTZ: 'Europe/Warsaw'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/booking
      POSTGRES_DB: booking
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  booking:
    depends_on:
      - postgresqldb
    image: "booking:0.5.19-SNAPSHOT"
    restart: always
    container_name: booking
    ports:
      - "8999:8080"
    logging:
      options:
        max-size: "10m"


volumes:
  postgres_booking_data:
  postgres: